version: "3.9"
services:
  jupyter_lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../:/tf
    entrypoint: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]